### PR TITLE
Feature: Add a "how to contribute to the doc" guide

### PR DESCRIPTION
**Pull request by syphax-bouazzouni**
### Context
See https://github.com/ontoportal/administration/issues/11

This PR adds a naive guide (just guided screenshots) of how to edit/contribute to this documentation, open for anyone who wants to consolidate it and make it more readable (redaction is not my strength)  

### Changes 

- Add a How to contribute to the doc page(https://github.com/ontoportal/administration/commit/05c84c120a7e6ea576aa3b60b6a04296284243d3)
- Move the old maintaining doc to the Configuration section(https://github.com/ontoportal/administration/commit/51f28649f27fac8a1cd51416a764e403ddf14f53)
- Don't display configuration docs in the sections tree (https://github.com/ontoportal/administration/pull/18/commits/620a8418e771aeb34c9a55c10b300827a98feb16)
 
image

- Reference to the  configuration docs in the home (https://github.com/ontoportal/administration/pull/18/commits/7deb12522b3094dcf3275e645647599b6c9d4ec0)
image

### Preview
https://ontoportal-lirmm.github.io/documentation/docs/documentation-docs/how-to-contribute-doc/

### CODE REVIEW

**Comment by xeniacs** [comment]
Thanks for the work Syphax! 
A clarification question: In Home - Contributing section, the Contributing Guide links to an ncbo repository. This will be replaced with a page in this documentation, correct? I guess we need to agree on the content of the guide, but the ncbo one could be our starting point.

**Review by xeniacs — APPROVED** [review]

**Comment by xeniacs** [comment]
Currently the "Edit this page link on GitHub" is https://github.com/ontoportal/administration/tree/main/docs/documentation-docs/how-to-contribute-doc.md and it gives 404.
What's the edit page for [the ontoportal-lirmm.github.io](https://ontoportal-lirmm.github.io/documentation/docs/documentation-docs/how-to-contribute-doc/)? I would like to try out the editing process.

**Comment by syphax-bouazzouni** [comment]
Hi @xeniacs 


> This will be replaced with a page in this documentation, correct? I guess we need to agree on the content of the guide, but the ncbo one could be our starting point.

Indeed, 



>  What's the edit page for [the ontoportal-lirmm.github.io](https://ontoportal-lirmm.github.io/documentation/docs/documentation-docs/how-to-contribute-doc/)? I would like to try out the editing process.

The ontoportal-lirmm.github.io is my local instance,  that I use only for testing and preview, if you want to edit the how to contribute, which is only present in this pull request (not merged) , you need to contribute to this pull request by doing like so: [how to edit contribute to an existent pull-request](https://ontoportal-lirmm.github.io/documentation/docs/documentation-docs/how-to-contribute-doc/#how-to-editcontribute-to-an-existent-pull-request)

**Comment by xeniacs** [comment]
Do I need editing rights? The Edit File choice is greyed out.

**Comment by syphax-bouazzouni** [comment]
@xeniacs I added you to the admins of this repo is it still greyed out?

**Comment by xeniacs** [comment]
Yes, still greyed out. Could it be because I've already approved the changes? I'll request to review again.

**Comment by xeniacs** [comment]
Aha!
image
I need to be in the correct branch to be able to edit it seems.

**Comment by syphax-bouazzouni** [comment]
@xeniacs I sent you an invitation to the [ontoportal-lirmm/documentation](https://github.com/ontoportal-lirmm/documentation/tree/feature/add-how-to-contribute-to-the-doc) repo. Because I did an error and created my branch there so only people from ontoportal-lirmm can edit this. Next time I (and we) will create our branches here so very can have access to edit it.

And normally the greyed-out will not be there.

**Review by xeniacs — APPROVED** [review]

**Review by graybeal — APPROVED** [review]

**Comment by jonquet** [comment]
Good to me indeed. This is still setting up the stucture of the doc.
I have not yet contibuted to the content.

**Pull request merged**
